% sliderandedit
function mygui
figure;
set(gcf,'toolbar','none')
set(gcf,'menubar','none')
set(gcf,'DefaultUicontrolBackgroundColor','default',...
    'defaultuicontrolunits','normalized')
th = uicontrol('Style', 'text',...
    'String', '输入值或移动滚动条',...
    'backgroundcolor','default',...
    'fontsize',20,...
    'Position', [0.2 0.8 0.6 0.1]);

eh = uicontrol('Style', 'edit',...
    'String', '0',...
    'backgroundcolor','default',...
    'fontsize',10,...
    'Position', [0.2 0.5 0.6 0.1],...
    'Callback', @edit1_Callback);

sh = uicontrol('Style', 'slider',...
    'String', 'fgdfg',...
    'backgroundcolor','default',...
    'Position', [0.2 0.2 0.6 0.1],...
    'Callback', @slider1_Callback);

numerrors=0;

function edit1_Callback(hObject, eventdata, handles)
    val=str2double(get(eh,'string'));
    if isnumeric(val)&...
            length(val)==1&...
            val>=get(sh,'min')&...
            val<=get(sh,'max')
        set(sh,'value',val);
    else
        numerrors=numerrors+1;
        set(eh,'string',['have entered an invalid entry ',...
            num2str(numerrors),' times'])
    end
end
function slider1_Callback(hObject, eventdata, handles)
set(eh,'string',...
    num2str(get(sh,'value')));
end
end