%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 《实战MATLAB之文件与数据接口技术》附加程序
% 作  者：江泽林 刘维
% 出版社：北京航空航天大学出版社
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [methodinfo,structs,enuminfo,ThunkLibName]=dlladdtype
%DLLADDTYPE Create structures to define interfaces found in 'dlladd'.

%This function was generated by loadlibrary.m parser version 1.1.6.38 on Tue Jul 16 22:29:44 2013
%perl options:'dlladd.i -outfile=dlladdtype.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
%  double addDoubleS ( double v1 , double v2 ); 
fcns.name{fcnNum}='addDoubleS'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='double'; fcns.RHS{fcnNum}={'double', 'double'};fcnNum=fcnNum+1;
%  void addDoubleV ( double * v1 , const double * v2 , int size ); 
fcns.name{fcnNum}='addDoubleV'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'doublePtr', 'doublePtr', 'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;